export const shields = [
  {
    id: 1,
    img: "https://img.shields.io/badge/HTML5-E34F26?style=flat&logo=html5&logoColor=white",
    alt: "HTML",
    category: "good",
  },
  {
    id: 2,
    img: "https://img.shields.io/badge/CSS3-1572B6?style=flat&logo=css3&logoColor=white",
    alt: "CSS",
    category: "good",
  },
  {
    id: 3,
    img: "https://img.shields.io/badge/Bootstrap-7952B3?style=flat&logo=bootstrap&logoColor=white",
    alt: "Bootstrap",
    category: "good",
  },
  {
    id: 4,
    img: "https://img.shields.io/badge/Tailwind_CSS-38B2AC?style=flat&logo=tailwind-css&logoColor=white",
    alt: "Tailwind CSS",
    category: "good",
  },
  {
    id: 5,
    img: "https://img.shields.io/badge/JavaScript-F7DF1E?style=flat&logo=javascript&logoColor=black",
    alt: "JavaScript",
    category: "good",
  },
  {
    id: 6,
    img: "https://img.shields.io/badge/React.js-61DAFB?style=flat&logo=react&logoColor=black",
    alt: "React.js",
    category: "good",
  },
  {
    id: 7,
    img: "https://img.shields.io/badge/Redux-764ABC?style=flat&logo=redux&logoColor=white",
    alt: "Redux",
    category: "good",
  },
  {
    id: 8,
    img: "https://img.shields.io/badge/Node.js-339933?style=flat&logo=node.js&logoColor=white",
    alt: "Node.js",
    category: "good",
  },
  {
    id: 9,
    img: "https://img.shields.io/badge/Express.js-000000?style=flat&logo=express&logoColor=white",
    alt: "Express.js",
    category: "comfortable",
  },
  {
    id: 10,
    img: "https://img.shields.io/badge/MongoDB-47A248?style=flat&logo=mongodb&logoColor=white",
    alt: "MongoDB",
    category: "good",
  },
  {
    id: 11,
    img: "https://img.shields.io/badge/Next.js-000000?style=flat&logo=next.js&logoColor=white",
    alt: "Next.js",
    category: "familiar",
  },
  {
    id: 12,
    img: "https://img.shields.io/badge/PostgreSQL-336791?style=flat&logo=postgresql&logoColor=white",
    alt: "postgresql",
    category: "familiar",
  },
  {
    id: 13,
    img: "https://img.shields.io/badge/Python-3776AB?style=flat&logo=python&logoColor=white",
    alt: "Python",
    category: "familiar",
  },
  {
    id: 14,
    img: "https://img.shields.io/badge/Kotlin-0095D5?style=flat&logo=kotlin&logoColor=white",
    alt: "Kotlin",
    category: "familiar",
  },
  {
    id: 15,
    img: "https://img.shields.io/badge/Firebase-FFCA28?style=flat&logo=firebase&logoColor=black",
    alt: "Firebase",
    category: "tools",
  },
  {
    id: 16,
    img: "https://img.shields.io/badge/Java-007396?style=flat&logo=java&logoColor=white",
    alt: "Java",
    category: "familiar",
  },
  {
    id: 15,
    img: "https://img.shields.io/badge/C-00599C?style=flat&logo=c&logoColor=white",
    alt: "C",
    category: "familiar",
  },
  {
    id: 17,
    img: "https://img.shields.io/badge/VS_Code-007ACC?style=flat&logo=visual-studio-code&logoColor=white",
    alt: "VS Code",
    category: "tools",
  },
  {
    id: 18,
    img: "https://img.shields.io/badge/TypeScript-007ACC?style=flat&logo=typescript&logoColor=white",
    alt: "TypeScript",
    category: "fimiliar",
  },
  {
    id: 19,
    img: "https://img.shields.io/badge/REST_API-FF5733?style=flat",
    alt: "REST API",
    category: "comfortable",
  },
];
